# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python Test Suite For Dating Web App

env:
  DB_KEY: ${{vars.DB_KEY}}
  SK_KEY: ${{vars.SK_KEY}}
  VISIT_LIMIT: ${{vars.VISIT_LIMIT}}
  REQUEST_LIMIT: ${{vars.REQUEST_LIMIT}}

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest fastapi[all]
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test if environment variables are accessed.
      run: |
        env
      
    - name: Run time is less than 5 seconds.
      run: |
        python run_tests.py --t matching_algorithm_test --c TestMatchingAlgorithmRunTime --f test_run_time

    - name: Run time is less than 5 seconds after multiple iterations.
      run: |
        python run_tests.py --t matching_algorithm_test --c TestMatchingAlgorithmRunTime --f test_run_time_multiple

    - name: Test to see if matching algorithm returns user profiles and their estimated similarity percentages.
      run: |
        python run_tests.py --t matching_algorithm_test --c TestMatchingAlgorithm --f test_match

    - name: Retrieve the top 5 users with the highest similarity scores.
      run: |
        python run_tests.py --t matching_algorithm_test --c TestMatchingAlgorithm --f test_similarity_scores

    - name: Retrieve the top k users with the highest similarity scores.
      run: |
        python run_tests.py --t matching_algorithm_test --c TestMatchingAlgorithm --f test_retrieve_top_k_users
      
    - name: Insert a user into a heap and ensure that the heap follows all the rules and there are no violations.
      run: |
        python run_tests.py --t matching_algorithm_test --c TestHeap --f test_insert

    - name: Delete users from the heap and check if the top user changes through different operations.
      run: |
        python run_tests.py --t matching_algorithm_test --c TestHeap --f test_delete_and_top

    - name: Change the rating of the user depending on whether they are rated positively, neutrally, or negatively.
      run: |
        python run_tests.py --t matching_algorithm_test --c TestRating --f test_change_rating

    - name: Check if root route is working.
      run: |
        python run_tests.py --t server_test --c TestBasicRoute --f test_simple_route

    - name: User should sign up if they are of or over the age of majority in their jurisdiction.
      run: |
        python run_tests.py --t server_test --c TestSignUpOps --f test_signup

    - name: User should be unable to sign up for an account if they are under the age of majority in their jurisdiction.
      run: |
        python run_tests.py --t server_test --c TestSignUpOps --f test_signup_if_underage
    
    - name: User should be able to log in if they have an account.
      run: |
        python run_tests.py --t server_test --c TestLoginOps --f test_login
    
    - name: Prevent a user from logging in if they do not have a valid token.
      run: |
        python run_tests.py --t server_test --c TestLoginOps --f test_login_with_invalid_token

    - name: Allow a user to use protected resources with valid token.
      run: |
        python run_tests.py --t server_test --c TestProtectedRouteOps --f test_protected_route_with_valid_token
      
    - name: Prevent a user from using protected resources with an invalid token.
      run: |
        python run_tests.py --t server_test --c TestProtectedRouteOps --f test_protected_route_with_invalid_token

    - name: Allow users to change their DOB if they registered for an account using a valid DOB. Otherwise, suspend/ban their account if they did not do so.
      run: |
        python run_tests.py --t server_test --c TestAppOps --f test_update_profile_DOB
    
    - name: User should search for other users based on a specific keyword they enter into the search bar.
      run: |
        python run_tests.py --t server_test --c TestAppOps --f test_search

    - name: Send a chat request to a user who registered for an account.
      run: |
        python run_tests.py --t server_test --c TestChatRequestOps --f test_CR_happy
    
    - name: Attempt to send a chat request to a user who did not register for an account.
      run: |
        python run_tests.py --t server_test --c TestChatRequestOps --f test_CR_sad

    - name: Approve a chat request sent by a user.
      run: |
        python run_tests.py --t server_test --c TestChatRequestOps --f test_approve_CR
    
    - name: Deny a chat request sent by a user.
      run: |
        python run_tests.py --t server_test --c TestChatRequestOps --f test_deny_CR
